on:
  release:
    types: [created]
    
jobs:
  release:
    name: Release and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $PUBLISHER_TOKEN"
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}